apiVersion: v1
kind: ServiceAccount
metadata:
  name: dailynotescloud-backend-sa
  namespace: default
  annotations:
    # Binds the Kubernetes Service Account to the GCP Google Service Account for Workload Identity
    iam.gke.io/gcp-service-account: "dailynotescloud-backend@YOUR_GCP_PROJECT.iam.gserviceaccount.com"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dailynotescloud-frontend-sa
  namespace: default
